
SELECT * FROM CAR_SALES_TRANSACTION 
WHERE OWNER = 'First Owner' AND
YEAR BETWEEN 2016 AND 2020 
AND KM_DRIVEN < 80000



SELECT * FROM CAR_SALES_TRANSACTION
WHERE MILEAGE BETWEEN '24' AND '26' AND
SEATS IN ('4','5')AND
FUEL = 'Diesel' AND
YEAR BETWEEN 2018 AND 2020



SELECT * FROM CAR_SALES_TRANSACTION 
JOIN SALES_STATUS USING (SALES_ID)
WHERE SOLD = 'N' AND
SELLER_TYPE IN ('Individual','Dealer') AND
KM_DRIVEN <60000 AND
YEAR BETWEEN 2014 AND 2020


SELECT * FROM CAR_SALES_TRANSACTION JOIN CITY_MASTER
USING (CITY_CODE)
WHERE MILEAGE BETWEEN '20' AND '25' AND
CITY_NAME IN('Mumbai', 'Kochi', 'Chennai', 'Delhi')



SELECT * FROM CAR_SALES_TRANSACTION JOIN SALES_STATUS
USING (SALES_ID)
WHERE NAME LIKE '%Honda%' AND 
OWNER IN ('First Owner','Second Owner') AND
FUEL = 'Petrol' AND
MILEAGE = '25' AND
SOLD = 'N' AND
SEATS > 4







